name: 'Cache Dependencies'
description: 'Set up Node.js, cache node_modules, and install dependencies'
runs:
  using: "composite"
  steps:
    - name: '⚙️ Use Node.js'
      uses: actions/setup-node@v3
      with:
        check-latest: true

    - name: 'Cache dependencies'
      uses: actions/cache@v3
      id: cache-deps
      with:
        path: node_modules
        key: node-deps-${{ hashFiles('**/package-lock.json') }}

    - name: '⛓️ Install dependencies'
      if: steps.cache-deps.outputs.cache-hit != 'true'
      run: npm ci --no-optional --no-audit --prefer-offline --progress=false
