name: Run Angular tests

on:
  pull_request_target:
    types: [opened, synchronize, reopened]

jobs:
  setup:
    name: 'Setup'
    uses: './.github/workflows/setup.yml'

  docs:
    name: 'Run Angular tests'
    runs-on: ubuntu-latest
    steps:
      - name: 'Test'
        run: npm test
